### ISSUE TITLE
Great tool, but I'm having some issues

### ISSUE THREAD

**Issue by jjones3286** [jordanwildon/Telepathy#1]
Hi Jordan!

I have been experimenting with your tool - great concept and I can certainly see a lot of great uses for this.

I am planning to write an article about it on my webpage if that is something you would be okay with? You can see the content I write here: https://os2int.com/toolbox

I have encountered some issues when using the tool. When I deployed forwards.py, no net.csv file is created. The edgelist populates quite nicely. Would you be able to clarify whether this is a bug on my side or whether I have missed something out?

**Comment by jordanwildon** [comment]
Hi there!

Thank you! I'm absolutely happy for you to write about the tool.

I've just tried to replicate this issue and the file is generating. I assume you selected yes to "Do you also want to scrape forwards from the discovered channels?" and therefore the issue could be that the tool creates the file and saves only after completing the process.

I'll mark this as a bug and look into how else to handle file saving. It might make sense for this to save as it goes instead of caching all the data and dumping it into a CSV at the end of the process.

**Comment by jjones3286** [comment]
Hi!

Thanks so much for replying.

Fantastic - I completely agree, I think it would be better to have the data saved as it goes. I tried to process a very large chatroom associated with the far-right yesterday - I also selected the option to scrape forwards from the discovered channels. As you can imagine, I think the data was too big to handle. So saving as it goes is a really good shout in my opinion.

**Comment by jordanwildon** [comment]
This has now been resolved, just needed to move a few lines around :)

**Comment by jjones3286** [comment]
Hi great stuff with the additional improvements! I have Just given forwards.py a new test and I'm getting the following after scraping the primary channel:

Forwards scraped successfully.
Do you also want to scrape forwards from the discovered channels? (y/n)y
Scraping forwards from channels discovered in britainfirstchat ...
Traceback (most recent call last):
  File "d:\Scripts\Python\Telepathy\forwards.py", line 120, in <module>
    client.loop.run_until_complete(new_main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\Scripts\Python\Telepathy\forwards.py", line 81, in new_main
    df = pd.read_csv('./edgelists/'+ alphanumeric + '_edgelist.csv')
  File "C:\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "C:\Python39\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "C:\Python39\lib\site-packages\pandas\io\parsers\base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "C:\Python39\lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './edgelists/britainfirstchat_edgelist.csv'

Is there an issue on my side that I need to fix? I did a clean install and setup, can't figure out if there is something else.

**Comment by jordanwildon** [comment]
Thanks! Upon quickly looking over this it seems that the issue might be with running this on Windows and Python’s os module having some issues with that. I’ll attempt to replicate this tomorrow on both Windows and Unix systems and try to get to the bottom of it. Shouldn’t be a difficult fix at all, and could just be due to how I’ve defined pathnames. Apologies that it’s come up with problems again!

**Comment by jordanwildon** [comment]
Checked this out and turns out it was because of how the file write permissions were granted. I've now tested this and it looks to be resolved. Will also give it a shot on windows to confirm that everything is still works across platforms.

**Comment by jjones3286** [comment]
Fantastic! Thanks so much! I will give it a re-test once you have given me the thumbs up ref the Windows environment.
