### ISSUE TITLE
Phone number ban with user lookup

### ISSUE THREAD

**Issue by osinter456** [jordanwildon/Telepathy#17]
hi
i try python3 telepathy.py -u telegramID

but any user are uknown : 

 [+] User details for 1XXXXXX
 [!] User not found, this is likely because Telepathy has not encountered them yet.

and after more test banned :

telethon.errors.rpcerrorlist.PhoneNumberBannedError: The used phone number has been banned from Telegram and cannot be used anymore. Maybe check https://www.telegram.org/faq_spam (caused by SendCodeRequest)
Erreur de segmentation (core dumped)

😢
thx for your project, best regard

**Comment by jordanwildon** [comment]
IDs cannot be looked up if they haven't been encountered by the account before. This could be made clearer in the documentation and I will update that.

As for the ban, this could be due to a number of things, but appears to be flooding the API with requests. This is not something I have any control over so therefore closing the issue.
