### ISSUE TITLE
Token not sent to telegram from config menu

### ISSUE THREAD

**Issue by radiophonic** [jordanwildon/Telepathy#61]
Hi there, thanks for your work on this software. It appears to be just what I need for an active investigation.

However, after entering my API information I'm unable to get past "Please enter your phone (or bot token):" as no token is sent to my telegram client(s).

Any advice would be great.

Thanks!

**Comment by proseltd** [comment]
Hi there, 

This is (usually) due to a requirement to enter your phone number for a second time after you've already entered it. I believe it was based on a change to Telegram/Telethon. 

If you reenter your phone number again at the "Please enter your phone (or bot token):", does it allow you to continue?
