### ISSUE TITLE
[Feature Request] Scrape comments on channel posts

### ISSUE THREAD

**Issue by fabrei** [jordanwildon/Telepathy#7]
Hi,

thanks for developing this nice tool =)

In the [upcoming changes](https://github.com/jordanwildon/Telepathy#upcoming-changes) you want to implement the ability to scrape comments in channel posts:

> Giving the archiver module the ability to archive comments on channel posts.

This would be a nice feature; do you have an idea when it is ready?

**Comment by jordanwildon** [comment]
Hey there.

Right now I’m not certain on the timeframe. Between everything else happening I’ve taken a bit of a pause of major developments to Telepathy.

A current workaround is already included with the scripts available—channels that have comments enabled will have an associated group, by archiving that group as well as the channel it’s theoretically possible to cross reference the channel post ID with the reply ID of messages within the group. This is a bit awkward right now, but at least provides the basics.

**Comment by aaarghhh** [comment]
My PR does exactly that feature you looking for.  The flag -r will generate a new file in the archive directory. 
PS: why my PR was closed and not merged?

**Comment by jordanwildon** [comment]
This has perplexed me, I definitely hit merge on it, and didn’t select to close it at all. Really confused at to what happened there

**Comment by aaarghhh** [comment]
Don''t worry was my issue.  I used Pycharm which was binded to an email that isn't in Github. When I pushed the commit I used an unrecognized email and Github wasn't able to match my account. I fixed it just adding a secondary emails in profile. There are tools that parse repos in order to find information about this, the email is in cleartext inside the commit ^^.
